---
# tasks file for haproxy
- name: Install haproxy
  yum: name=haproxy state=present

- name: haproxy service
  service: name=haproxy state=started enabled=yes

- name: copy haproxy.cfg
  copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
  notify:
  - restart haproxy

- name: download haproxy.sh script
  get_url:
  args:
    #url: http://cs312.osuosl.org/_static/hw/haproxy.sh
    url: https://goo.gl/xkB6DB
    dest: /tmp/haproxy.sh
    mode: 755

- name: run haproxy.sh
  command: /tmp/haproxy.sh creates=/tmp/proj3
